name: Check site http status code

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: HTTP_STATUS_CODE=$(curl -I -m 15 -s -w "%{http_code}\n" -o /dev/null https://fanswoo.com)
        
      - name: Notify Slack failed notification
        if: $HTTP_STATUS_CODE !== 200
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ':no_entry: 正式站佈署失敗'
          SLACK_MESSAGE: '@sacriley 偵測到網站運作中斷，請立刻確認網站在線狀態'
          SLACK_FOOTER: ''
          SLACK_LINK_NAMES: true
          MSG_MINIMAL: commit,actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
