name: Check site http status code

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          HTTP_STATUS_CODE=$(curl -I -m 15 -s -w "%{http_code}\n" -o /dev/null https://fanswoo.com)
          echo "HTTP_STATUS_CODE=$HTTP_STATUS_CODE" >> $GITHUB_ENV
          echo $HTTP_STATUS_CODE
        
      - name: Notify Slack failed notification
        if: ${{ env.HTTP_STATUS_CODE != 200 }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ':no_entry: 正式站運作中斷'
          SLACK_MESSAGE: '@sacriley 偵測到網站運作中斷，請立即確認網站在線狀態'
          SLACK_FOOTER: ''
          SLACK_LINK_NAMES: true
          MSG_MINIMAL: commit,actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
