name: Check site http status code

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2
        
      - name: check
        run: ./http-status-code-checker.sh
        
      - name: Notify Slack failed notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ':no_entry: 正式站運作中斷'
          SLACK_MESSAGE: '@sacriley 偵測到網站運作中斷，請立即確認網站在線狀態'
          SLACK_FOOTER: ''
          SLACK_LINK_NAMES: true
          MSG_MINIMAL: commit,actions url
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
